export default {
  "language.selector.title": "Language",
  "profile.title": "Sean Lin's profile",
  "about.me.title": "AboutMe",
  "about.me.list.react": "2+ years experience with popular React.js framework and workflows (Redux)",
  "about.me.list.webpack": "Experience with common front-end development tools such as Babel, Webpack, NPM, etc.",
  "about.me.list.get": "Familiarity with VCS (Git)",
  "about.me.list.team.player": "Team Player",
  "about.me.list.time.manage": "Good time-management skills",
  "about.me.list.product": "Ability to understand business requirements, help PM translate requirements into technical solutions",
  "about.me.list.ui.ix": "High UI / UX sense, discuss with designer for the better user experience",
  "about.me.list.cross.browser": "Knowledge of cross browser compatibility",
  "skill.title": "Skills",
  "experience.title": "Experiences",
  "experience.accupass.name": "Accupass 活動通",
  "experience.accupass.duration": "Jun 2018 - Now",
  "experience.accupass.job.title": "Front-end Developer",
  "experience.accupass.job.website": "Mainly responsible for front-end development of the official website of Accupass, the largest event platform in Asia, cooperate with 3 back-end developers and 2 others front-end developers in RD team, build a responsive website with good user experience.",
  "experience.accupass.job.support": "Support special project from other department, develop including single-page campaign, landing page or theme event website.",
  "experience.accupass.job.git": "Optimize workflow of front-end team, make deployment more easier.",
  "experience.accupass.job.refactor": "Interest in the new release of open source library, remove legacy method and function, refactor make things easier.",
  "experience.accupass.job.ux": "Good concept and sense for user experience, always stand at user’s point to provide the best possible solution for UI/UX designers.",
  "experience.leo.name": "Leosys 國眾電腦",
  "experience.leo.duration": "Feb 2017 - Jun 2018",
  "experience.leo.job.title": "MIS maintenance engineer / Front-end Developer",
  "experience.leo.job.maintain": "Maintain internal ERP, CRM system, including basic SQL operation, old system bug fix, new feature with HTML/CSS/JavaScript.",
  "experience.leo.job.develop": "Design and develop a work dispatch system for internal hardware-maintenance engineer, including map tracing, online work sheet fill-in, picture upload etc. , using React.js as front-end framework, and integrate with back-end RESTful API.",
  "contact.title": "Contact",
  "contact.name": "TZU HSUAN LIN",
}
