export default {
  "language.selector.title": "選擇語言",
  "profile.title": "Sean Lin's profile",
  "about.me.title": "AboutMe",
  "about.me.list.react": "兩年以上 React.js 框架以及工作流程經驗",
  "about.me.list.webpack": "熟悉前端開發工具，Babel、webpack、NPM...等",
  "about.me.list.get": "熟悉版本控制工具(Git)",
  "about.me.list.team.player": "善於團隊合作",
  "about.me.list.time.manage": "良好的時間管理",
  "about.me.list.product": "協助 PM 將業務需求轉化爲最佳的產品解決方案",
  "about.me.list.ui.ix": "與 UI / UX 設計師討論最佳使用者體驗",
  "about.me.list.cross.browser": "了解跨瀏覽器兼容性",
  "skill.title": "Skills",
  "experience.title": "Experiences",
  "experience.accupass.name": "Accupass 活動通",
  "experience.accupass.duration": "2018 六月 - 現今",
  "experience.accupass.job.title": "前端工程師",
  "experience.accupass.job.website": "主要負責亞洲最大活動平台 - Accupass 官方網站前端開發維護，與 RD 團隊中另外兩位前端、三位後端合作，打造體驗最好、操作流暢的 RWD 網站。",
  "experience.accupass.job.support": "支援其他部門的前端專案，開發單頁式廣告、宣傳頁或主題專區。",
  "experience.accupass.job.git": "優化前端團隊開發產品之 Git Flow，使版控與上版更順利。",
  "experience.accupass.job.refactor": "關注開源的最新寫法，重構現有程式與架構，廢除舊寫法。",
  "experience.accupass.job.ux": "具備良好的 UX 概念，站在使用者的角度提供 UI/UX 設計師最佳可行之方案。",
  "experience.leo.name": "Leosys 國眾電腦",
  "experience.leo.duration": "2017 二月 - 2018 六月",
  "experience.leo.job.title": "MIS 維運工程師 / 前端工程師",
  "experience.leo.job.maintain": "ERP/CRM 系統維運，包含 SQL 資料庫基本操作、舊功能維護、新功能前端修改(HTML/CSS/JavaScript)。",
  "experience.leo.job.develop": "設計與開發公司內部駐點維修工程師使用之工作外派系統，包含地圖追蹤位置、填寫維修單據、拍照上傳...等功能，前端使用 React.js 框架，與後端 RESTful API 做整合。",
  "contact.title": "Contact",
  "contact.name": "TZU HSUAN LIN",
}
